# python main.py --config ./config/refinment.json --seed 123 --suffix "seed_123_manual_slicing_epoch:100_batch_32" --step "feature_segmentor" --wandb_mode "online" --site 2 >>  ./train_record/head:seed_123_manual_slicing_epoch:100_batch_32.txt
# python main.py --suffix "ge_15_seed_123_with_head_saved_at_best_epoch"  --config ./config/refinment.json --step "refine" --wandb_mode "online" --seed 123 --site 1
# python main.py --suffix "philips_15_seed_123_with_head_saved_at_best_epoch"  --config ./config/refinment.json --step "refine" --wandb_mode "online" --seed 123 --site 3
# python main.py --suffix "philips_3_seed_123_with_head_saved_at_best_epoch"  --config ./config/refinment.json --step "refine" --wandb_mode "online" --seed 123 --site 4
# python main.py --suffix "siemens_15_seed_123_with_head_saved_at_best_epoch"  --config ./config/refinment.json --step "refine" --wandb_mode "online" --seed 123 --site 5
# python main.py --suffix "siemens_3_seed_123_with_head_saved_at_best_epoch"  --config ./config/refinment.json --step "refine" --wandb_mode "online" --seed 123 --site 6
# python main.py --config ./config/feature_seg.json --seed 42 --suffix "mms_seed:42" --step "feature_segmentor" --wandb_mode "online" --data "mms" --site "B" >>  ./train_record/head:seed_42_epoch:50_batch_32.txt
# python main.py --config ./config/feature_seg.json --seed 123 --suffix "mms_seed:123" --step "feature_segmentor" --wandb_mode "online" --data "mms" --site "B" >>  ./train_record/head:seed_123_epoch:50_batch_32.txt
# python main.py --config ./config/feature_seg.json --seed 12345 --suffix "mms_seed:12345" --step "feature_segmentor" --wandb_mode "online" --data "mms" --site "B" >>  ./train_record/head:seed_12345_epoch:50_batch_32.txt
# linscape Decay, seed 123
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:ge_15"       --config ./config/refinment.json --step "refine" --final_alpha 0.3 --wandb_mode "online" --seed 123 --site 1    >>    ./training/mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:ge_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:philips_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.3 --wandb_mode "online" --seed 123 --site 3    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:philips_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:philips_3"   --config ./config/refinment.json --step "refine" --final_alpha 0.3 --wandb_mode "online" --seed 123 --site 4     >>   ./training/mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:philips_3.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:siemens_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.3 --wandb_mode "online" --seed 123 --site 5    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:siemens_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:siemens_3"   --config ./config/refinment.json --step "refine"  --final_alpha 0.3 --wandb_mode "online" --seed 123 --site 6    >>    ./training/mixup_labels_linscape_decay_final_alpha:0.3_epoch_5_seed_123_target:siemens_3.txt
# # source activate udas

# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:ge_15"       --config ./config/refinment.json --step "refine" --final_alpha 0.4 --wandb_mode "online" --seed 123 --site 1    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:ge_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:philips_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.4 --wandb_mode "online" --seed 123 --site 3    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:philips_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:philips_3"   --config ./config/refinment.json --step "refine" --final_alpha 0.4 --wandb_mode "online" --seed 123 --site 4     >>   ./training/mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:philips_3.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:siemens_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.4 --wandb_mode "online" --seed 123 --site 5    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:siemens_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:siemens_3"   --config ./config/refinment.json --step "refine" --final_alpha 0.4 --wandb_mode "online" --seed 123 --site 6    >>   ./training/mixup_labels_linscape_decay_final_alpha:0.4_epoch_5_seed_123_target:siemens_3.txt
# # alpha = 0.5
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:ge_15"       --config ./config/refinment.json --step "refine" --final_alpha 0.5 --wandb_mode "online" --seed 123 --site 1     >>  ./training/mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:ge_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:philips_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.5 --wandb_mode "online" --seed 123 --site 3     >>  ./training/mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:philips_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:philips_3"  --config ./config/refinment.json --step "refine" --final_alpha 0.5 --wandb_mode "online" --seed 123 --site 4      >>  ./training/mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:philips_3.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:siemens_15"  --config ./config/refinment.json --step "refine" --final_alpha 0.5 --wandb_mode "online" --seed 123 --site 5     >> ./training/mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:siemens_15.txt
# python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:siemens_3"  --config ./config/refinment.json --step "refine" --final_alpha 0.5 --wandb_mode "online" --seed 123 --site 6     >>  ./training/mixup_labels_linscape_decay_final_alpha:0.5_epoch_5_seed_123_target:siemens_3.txt




#test
python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.1_epoch_5_seed_123_target:ge_15" --config ./config/test_config.json --step "test" --final_alpha 0.2 --wandb_mode "online" --seed 123 --site 1 --test test --checkpoint "/home/sidra/Documents/Domain_Apatation/UDAS/src/checkpoints/refine_mixup_labels_linscape_decay_final_alpha:0.1_epoch_5_seed_123_target:ge_15_2023-09-20_10-33-11_AM/dc_model.pth"  >> ./training/test_mixup_labels_linscape_decay_final_alpha:0.1_epoch_5_seed_123_target:ge_15.txt
python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.2_epoch_5_seed_123_target:philips_15" --config ./config/test_config.json --step "test" --final_alpha 0.2 --wandb_mode "online" --seed 123 --site 3 --test test --checkpoint "/home/sidra/Documents/Domain_Apatation/UDAS/src/checkpoints/
python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.2_epoch_5_seed_123_target:philips_3" --config ./config/test_config.json --step "test" --final_alpha 0.2 --wandb_mode "online" --seed 123 --site 4 --test test --checkpoint  "/home/sidra/Documents/Domain_Apatation/UDAS/src/checkpoints/
python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.2_epoch_5_seed_123_target:siemens_15" --config ./config/test_config.json --step "test" --final_alpha 0.2 --wandb_mode "online" --seed 123 --site 5 --test test --checkpoint  "/home/sidra/Documents/Domain_Apatation/UDAS/src/checkpoints/
python main.py --data "cc359"  --suffix "mixup_labels_linscape_decay_final_alpha:0.2_epoch_5_seed_123_target:siemens_3" --config ./config/test_config.json --step "test" --final_alpha 0.2 --wandb_mode "online" --seed 123 --site 6 --test test --checkpoint  "/home/sidra/Documents/Domain_Apatation/UDAS/src/checkpoints/